# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160506_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 9, 27, 28, 458375, tzinfo=utc), verbose_name='date found'),
        ),
        migrations.AddField(
            model_name='founditems',
            name='desciption',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 9, 27, 28, 457441, tzinfo=utc), verbose_name='date lost'),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
