# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160506_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date found'),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date lost'),
        ),
    ]
